version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
jobs:
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: install dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: npm-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
            - ~/.cache/Cypress
      - run:
          command: pnpm nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: install dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: npm-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
            - ~/.cache/Cypress
      - nx/set-shas

      - run: pnpm nx-cloud start-ci-run --stop-agents-after="e2e"

      - run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t lint,test,build --parallel=3 --configuration=ci
      - run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t e2e --parallel=1

      - run: pnpm nx-cloud stop-all-agents
workflows:
  build:
    jobs:
      - agent:
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main
